var moneyGive = 1000;
var orangePrice = 400;
var applePrice = 300;
var totalCost = orangePrice + applePrice;
var retrunPrice = moneyGive - totalCost;
// console.log(retrunPrice);
var math = 75.25;
var biology = 65;
var chemistry = 80;
var physics = 35.45;
var bangla = 99.50;
var totalMarks = math + biology + chemistry + physics + bangla;
var averageMarks = totalMarks / 5;
var averageDecimal = averageMarks.toFixed(2);
averageDecimal = parseFloat(averageDecimal);
// console.log(averageDecimal);
var number = 119;
var reminder = 5;
console.log(number % reminder);